import crypto from "crypto";
import type { Request, Response } from "express";
import { Cart } from "../models/Cart.js";
import { Order } from "../models/Order.js";
import { Product } from "../models/Product.js";
import { User } from "../models/User.js";
import type { AuthRequest } from "../middleware/auth.middleware.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { createAppError } from "../middleware/error.middleware.js";
import { env } from "../config/env.js";
import { initializePaystackPayment, verifyPaystackPayment } from "../services/paystack.service.js";
import { sendOrderConfirmation } from "../services/email.service.js";

export const createOrder = asyncHandler(async (req: AuthRequest, res: Response) => { const cart = await Cart.findOne({ user: req.user!.id }).populate("items.product"); if (!cart || cart.items.length === 0) throw createAppError("Your cart is empty", 400); const items = []; let subtotal = 0; for (const cartItem of cart.items) { const product = cartItem.product as unknown as { _id: { toString(): string }; name: string; price: number; stock: number; images: Array<{ url: string }> }; const quantity = cartItem.quantity ?? 0; if (!product || product.stock < quantity) throw createAppError("One or more items are unavailable", 409); subtotal += product.price * quantity; items.push({ product: product._id, name: product.name, image: product.images[0]?.url ?? "", price: product.price, quantity, size: cartItem.size, color: cartItem.color }); } const shippingFee = 0; const currency = "USD" as const; const chargeCurrency = "NGN" as const; const total = subtotal + shippingFee; const chargeAmount = Math.round(total * env.USD_TO_NGN_RATE); const reference = `yag_${crypto.randomUUID().replace(/-/g, "")}`; const order = await Order.create({ user: req.user!.id, orderNumber: `YAG-${Date.now().toString().slice(-8)}`, items, shippingAddress: req.body.shippingAddress, subtotal, shippingFee, total, currency, payment: { provider: "paystack", reference, status: "pending", chargeAmount, chargeCurrency, exchangeRate: env.USD_TO_NGN_RATE } }); const user = await User.findById(req.user!.id); if (!user) throw createAppError("User not found", 404); const payment = await initializePaystackPayment(user.email, chargeAmount, reference, chargeCurrency); res.status(201).json({ success: true, message: "Order created. Complete payment to confirm it.", data: { order, payment } }); });
export const verifyOrderPayment = asyncHandler(async (req: AuthRequest, res: Response) => { const reference = String(req.params.reference); const order = await Order.findOne({ "payment.reference": reference, user: req.user!.id }); if (!order) throw createAppError("Order not found", 404); const payment = await verifyPaystackPayment(reference); if (payment.status !== "success") throw createAppError("Payment has not completed", 409); await markPaid(order.id, payment.paidAt); res.json({ success: true, message: "Payment verified", data: await Order.findById(order.id) }); });
async function markPaid(orderId: string, paidAt?: string): Promise<void> { const order = await Order.findById(orderId); const payment = order?.payment; if (!order || !payment || payment.status === "success") return; for (const item of order.items) { const quantity = item.quantity ?? 0; const result = await Product.findOneAndUpdate({ _id: item.product, stock: { $gte: quantity } }, { $inc: { stock: -quantity } }); if (!result) throw createAppError("An item is out of stock", 409); } payment.status = "success"; payment.paidAt = paidAt ? new Date(paidAt) : new Date(); order.status = "paid"; await order.save(); await Cart.findOneAndUpdate({ user: order.user }, { $set: { items: [] } }); const user = await User.findById(order.user); if (user) await sendOrderConfirmation(user.email, order); }
export const paystackWebhook = asyncHandler(async (req: Request, res: Response) => { const event = (Buffer.isBuffer(req.body) ? JSON.parse(req.body.toString("utf8")) : req.body) as { event?: string; data?: { reference?: string; paid_at?: string } }; if (event.event === "charge.success" && event.data?.reference) { const order = await Order.findOne({ "payment.reference": event.data.reference }); if (order) await markPaid(order.id, event.data.paid_at); } res.sendStatus(200); });
export const listOrders = asyncHandler(async (req: AuthRequest, res: Response) => { const filter = req.user!.role === "admin" ? {} : { user: req.user!.id }; const orders = await Order.find(filter).populate("user", "name email").sort("-createdAt"); res.json({ success: true, message: "Orders retrieved", data: orders }); });
export const updateOrderStatus = asyncHandler(async (req: AuthRequest, res: Response) => { const status = req.body.status as string; if (!["processing", "shipped", "delivered", "cancelled"].includes(status)) throw createAppError("Invalid order status", 400); const order = await Order.findByIdAndUpdate(req.params.id, { status }, { new: true }); if (!order) throw createAppError("Order not found", 404); res.json({ success: true, message: "Order updated", data: order }); });
